<?php
/**
 * Standards and Documentation page view.
 *
 * @package Ai_Tamer
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="wrap aitamer-wrap">

	<div class="aitamer-page-header">
		<div>
			<h1 class="aitamer-page-title"><?php esc_html_e( 'Technical Standards & Documentation', 'ai-tamer' ); ?></h1>
			<p class="aitamer-page-desc"><?php esc_html_e( 'How AI Tamer implements global standards for content provenance and protection.', 'ai-tamer' ); ?></p>
		</div>
	</div>

	<div class="aitamer-grid">
		<div class="aitamer-card">
			<h2 class="aitamer-card-title"><?php esc_html_e( 'Our Defense Strategy', 'ai-tamer' ); ?></h2>
			<p class="aitamer-intro">
				<?php esc_html_e( 'AI Tamer is not just a bot blocker; it is a content integrity system. We follow global standards to ensure that AI agents recognize your authority over your content.', 'ai-tamer' ); ?>
			</p>
			
			<div class="aitamer-standard-item">
				<h3><?php esc_html_e( 'C2PA & Verifiable Provenance', 'ai-tamer' ); ?></h3>
				<p><strong><?php esc_html_e( 'Why:', 'ai-tamer' ); ?></strong> <?php esc_html_e( 'Providing a "Proof of Human Origin" helps future AI-driven search engines (like Perplexity or Google AI Overviews) trust your data. By signing your content, you distinguish it from the flood of low-quality synthetic data.', 'ai-tamer' ); ?></p>
				<p><em><?php esc_html_e( 'Implementation:', 'ai-tamer' ); ?></em> <?php esc_html_e( 'We attach a DigitalDocument manifest with a SHA-256 integrity hash to every supported post.', 'ai-tamer' ); ?></p>
				<p><a href="https://c2pa.org/specifications/" target="_blank" class="button button-link"><?php esc_html_e( 'C2PA Technical Specs', 'ai-tamer' ); ?></a></p>
			</div>

			<div class="aitamer-standard-item">
				<h3><?php esc_html_e( 'Direct Directives (Schema.org)', 'ai-tamer' ); ?></h3>
				<p><strong><?php esc_html_e( 'Why:', 'ai-tamer' ); ?></strong> <?php esc_html_e( 'Modern AI bots look for these specific fields to determine if they have permission to use your work for training. Being explicit here is your first line of legal and technical defense.', 'ai-tamer' ); ?></p>
				<p><em>usageInfo & acquireLicensePage:</em> <?php esc_html_e( 'Standard properties to link your AI usage policy and training licenses.', 'ai-tamer' ); ?></p>
				<p><a href="https://schema.org/usageInfo" target="_blank" class="button button-link"><?php esc_html_e( 'Schema.org Reference', 'ai-tamer' ); ?></a></p>
			</div>

			<div class="aitamer-standard-item">
				<h3><?php esc_html_e( 'Deep Defense (IPTC Media Metadata)', 'ai-tamer' ); ?></h3>
				<p><strong><?php esc_html_e( 'Why:', 'ai-tamer' ); ?></strong> <?php esc_html_e( 'If an image is scraped or downloaded, it loses its connection to your site. By injecting IPTC metadata directly into the file, your "Human Origin" certification travels with the asset itself.', 'ai-tamer' ); ?></p>
				<p><em>Digital Source Type:</em> <?php esc_html_e( 'We use "originalMediaDigitalSource" to certify the asset was captured by a human, not generated by an algorithm.', 'ai-tamer' ); ?></p>
				<p><strong><?php esc_html_e( 'How to Certify:', 'ai-tamer' ); ?></strong> <?php esc_html_e( 'Go to your Media Library, edit any image, and check the "Human Origin" box. The metadata will be injected permanently into the file.', 'ai-tamer' ); ?></p>
				<p><a href="https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#digital-source-type" target="_blank" class="button button-link"><?php esc_html_e( 'IPTC Standards', 'ai-tamer' ); ?></a></p>
			</div>



			<div class="aitamer-standard-item">
				<h3>AI-Specific Robots Directives</h3>
				<p><?php esc_html_e( 'We support granular control for modern AI crawlers through robots.txt and X-Robots-Tag.', 'ai-tamer' ); ?></p>
				<p><strong>GPTBot:</strong> <a href="https://platform.openai.com/docs/gptbot" target="_blank"><?php esc_html_e( 'OpenAI Documentation', 'ai-tamer' ); ?></a></p>
				<p><strong>Google-Extended:</strong> <a href="https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers#google-extended" target="_blank"><?php esc_html_e( 'Google Documentation', 'ai-tamer' ); ?></a></p>
			</div>

			<div class="aitamer-standard-item">
				<h3><?php esc_html_e( 'llms.txt — Machine-Readable Sitemap', 'ai-tamer' ); ?></h3>
				<p><strong><?php esc_html_e( 'Why:', 'ai-tamer' ); ?></strong> <?php esc_html_e( 'Large Language Models (LLMs) and RAG agents need a way to quickly discover which content is available and what the licensing terms are without crawling every page.', 'ai-tamer' ); ?></p>
				<p><em><?php esc_html_e( 'Implementation:', 'ai-tamer' ); ?></em> <?php esc_html_e( 'When enabled in General Settings, AI Tamer serves a dynamic /llms.txt file that points agents to your machine-readable Catalog and License endpoints.', 'ai-tamer' ); ?></p>
				<p><a href="<?php echo esc_url( home_url( '/llms.txt' ) ); ?>" target="_blank" class="button button-link"><?php esc_html_e( 'View your llms.txt', 'ai-tamer' ); ?></a></p>
			</div>
		</div>

		<div class="aitamer-card sidebar">
			<h2 class="aitamer-card-title"><?php esc_html_e( 'Technical Architecture', 'ai-tamer' ); ?></h2>
			<div class="aitamer-info-box">
				<h4>CreativeWork vs DigitalDocument</h4>
				<p><?php esc_html_e( 'Instead of using ClaimReview (fact-checking), AI Tamer extends CreativeWork with custom properties or uses DigitalDocument with a hash-based identifier to ensure content integrity.', 'ai-tamer' ); ?></p>
			</div>
			<div class="aitamer-info-box tip">
				<h4><?php esc_html_e( 'Pro Tip', 'ai-tamer' ); ?></h4>
				<p><?php esc_html_e( 'Implementing iptc:DigitalSourceType is currently the gold standard for certifying human vs. AI origin in professional media workflows.', 'ai-tamer' ); ?></p>
			</div>
		</div>
	</div>

</div>
<style>
.aitamer-standard-item { margin-bottom: 25px; padding-bottom: 20px; border-bottom: 1px solid #eee; }
.aitamer-standard-item:last-child { border-bottom: none; }
.aitamer-standard-item h3 { margin-top: 0; color: #1d2327; }
.aitamer-info-box { background: #f0f6fb; padding: 15px; border-radius: 4px; margin-bottom: 20px; border-left: 4px solid #72aee6; }
.aitamer-info-box.tip { border-left-color: #68de7c; background: #f2fbf4; }
.aitamer-info-box h4 { margin-top: 0; margin-bottom: 10px; }
.aitamer-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 20px; }
@media (max-width: 782px) { .aitamer-grid { grid-template-columns: 1fr; } }
</style>
